spring:
  profiles:
    active: secrets # 민감 정보 포함 파일

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/ecommerce_db
    #url: jdbc:mysql://mysql-db:3306/ecommerce_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587 # Gmail SMTP 포트 (TLS)
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, loggers

scheduler:
  order:
    sync-time: "0 1 * * * *" # 매 시간 1분에 실행
  flash-sale:
    open-time: "0 0 14 * * *" # 매일 오후 2시에 실행
    close-time: "0 0 15 * * *" # 매일 오후 3시에 실행

logging:
  level:
    root: INFO
    com.mjyoo.limitedflashsale: DEBUG
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO
      springframework:
        cache: TRACE
        web: INFO
        security: INFO
        redis: DEBUG
#        web: INFO
#        security: INFO
#        http: INFO
#        test: DEBUG
