spring:
  config:
    import: classpath:/application-secrets.yml

  application:
    name: LimitedFlashSale
  datasource:
    url: jdbc:mysql://localhost:3308/ecommerce_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587 # Gmail SMTP ??? port (TLS): 587 ??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

security:
  jwt-secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.http: INFO
    org.springframework: INFO
    org.hibernate: INFO